### ISSUE TITLE
script.js not working

### ISSUE THREAD

**Issue by default-writer** [codejamninja/python-env#1]
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting chardet (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/c
hardet/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/c
hardet/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/c
hardet/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/c
hardet/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/c
hardet/
  Could not fetch URL https://pypi.org/simple/chardet/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/chard
et/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement chardet (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for chardet (from -r requirements.txt (line 1))
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Cause
d by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by default-writer** [comment]
[requirements.txt](https://github.com/codejamninja/python-env/files/2883307/requirements.txt)

**Comment by clayrisser** [comment]
Can you send me a link to a git repo that reproduces this issue?

**Comment by default-writer** [comment]
@codejamninja, it is not about my system config or a code base, this ticket about configuration of you libs, your configuration does not check for openssl and do not include python version with sslenabled flag, so, your embedded Pyhon interpreter is not aware of https pip repositories. Any case, send my dxdiag, may be it is some fun thought.
[DxDiag.txt](https://github.com/codejamninja/python-env/files/2888117/DxDiag.txt)

**Comment by clayrisser** [comment]
If you can send me an example setup with modules that require openssl, that will help me be able to debug it faster.

**Comment by default-writer** [comment]
@codejamninja ok, this is my setup

**Comment by default-writer** [comment]
@codejamninja here my sample project
![image](https://user-images.githubusercontent.com/383256/53152468-b9e37880-35c6-11e9-9308-329d4473a430.png)
https://github.com/hack2root/python-env

**Comment by default-writer** [comment]
@codejamninja error while install pip reqirements
![image](https://user-images.githubusercontent.com/383256/53153991-b3ef9680-35ca-11e9-8489-64b40c417715.png)

**Comment by clayrisser** [comment]
I tried this on my Linux and it worked without giving me an ssl error. What operating system are you running this on?

**Comment by clayrisser** [comment]
So, on Windows I am using Anaconda Python under the hood. Apparently, the problem is that Anaconda Python ships with its own SSL libraries and does not use the system SSL libraries when compiling the Python ssl module.

https://stackoverflow.com/questions/45908938/python-cant-connect-to-https-url-because-the-ssl-module-is-not-available

I'm not exactly sure what the best approach to load the ssl module into Anaconda Python is. Technically, I'm installing Anaconda Python and using it to create a virtualenv. This is due to Windows terrible support for python.

One possible suggestion would be to try using python2.

```sh
npm install --save python-env@python2
```

If you can figure out how to load the ssl module, let me know and I will add it into the code.

**Comment by default-writer** [comment]
> If you can figure out how to load the ssl module, let me know and I will add it into the code.

i fugured out that if i simply replace python-env binaries with standart official python3 binaries for windows, everything including pip, and ssl libraries start to work, try it out under windows, this is a desired behavior, because standart python executables built with ssl support, and your anaconda version deployed as standalone ("portable") Python, isn't. yes, it just because i rely on ("portable") version, and not OS dependent, so, despte i have failed to run python-enb onder windows, suppose you have to report anaconda or, precisely, minconda developers that they ship Python version without -ssl enabled option while pre-build python libraries, for windows users.
